backend:
  name: git-gateway
  branch: main  # or the branch you want to edit
  identity_url: https://YOUR-NETLIFY-SITE.netlify.app/.netlify/identity
  gateway_url: https://YOUR-NETLIFY-SITE.netlify.app/.netlify/git

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
